[package]
name = "substrate-debug-derive"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
syn = "1.0.5"

[features]
std = []

[dev-dependencies]

